name: standup_games
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_bloc: ^8.0.1
  go_router: ^3.0.1
  rxdart: ^0.27.3
  get_it: ^7.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  isar: 2.2.0+1
  isar_flutter_libs: 2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 2.2.0+1
  build_runner: any
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
